import type { Metadata } from "next";
import { Flow_Block, Kumbh_Sans } from "next/font/google";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kumbSans = Kumbh_Sans({
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-kumbh",
  preload: true,
});

const newsreader = localFont({
  src: "./fonts/newsreader-latin-600-normal.woff",
  variable: "--font-newsreader",
  weight: "600",
});

const flowBlock = Flow_Block({
  weight: "400",
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-block",
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kumbSans.variable} ${newsreader.variable} ${flowBlock.variable} antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
